# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VDIP
                                 A QGIS plugin
 It computes site-specific soil line using NIR-Red band spectral space. Further, it estimates vegetation and drought indices.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-17
        copyright            : (C) 2022 by Neha K Nawandar
        email                : nehanawandar@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VDIP class from file VDIP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .VDIP import VDIP
    return VDIP(iface)
